version: "3.7"
services:
  db:
    image: postgres
    container_name: lireddit-postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lireddit
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  cache:
    image: redis
    container_name: lireddit-redis
    volumes:
      - ./.cachedata:/data
    ports:
      - '6379:6379'
